[package]
name = "uart_host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpb3_lib = {path = "../rpb3_lib"}
serialport = "4.0.1"
